### ISSUE TITLE
Provide port to Python 3

### ISSUE THREAD

**Issue by kin5** [vladmunteanu/th2c#27]
According to [PEP 373](http://legacy.python.org/dev/peps/pep-0373/), the End Of Life date for Python 2 is 2020 (less than two years from the time of this issue). According to [PEP 404](http://legacy.python.org/dev/peps/pep-0404/) it is further cemented that Python 2 will no longer be actively developed due to their not being a Python 2.8 planned.

For the sake of the project's longevity it is in its best interest to, at the very least, provide a port to Python 3.

The project looks great and I would hate to see it fall to the wayside solely due to it being made for Python 2.x.

**Comment by harryf** [comment]
The current version of Redhat - RHEL 7 - which most banks, large enterprises etc. comes with a system python version of 2.7.5 and you need to jump through hoops to install Python 3.x ( e.g. https://stackoverflow.com/questions/8087184/problems-installing-python3-on-rhel )

**Comment by vladmunteanu** [comment]
Thanks for submitting this issue @kin5 !
Indeed, supporting Python 3 would be nice and that's the plan in the following weeks.

Tornado 5.0 has also been released and it has brought improvements regarding compatibility with  asyncio.
(http://www.tornadoweb.org/en/stable/releases/v5.0.0.html).

In case you want to have a go at it yourself, pull requests are appreciated!
