### ISSUE TITLE
Tornado write buffer blocked durig when sendindg requests for a long period of time (60 seg)

### ISSUE THREAD

**Issue by mabdelndi** [vladmunteanu/th2c#29]
Seems the client which is using the write buffer to flush de data obtained from h2 is not able to send data after a certain amount of time sending reqs (PUTs) writing it in the buffer but not realising them towards the server. Is this an expected behaviour or am i missing something?

**Comment by vladmunteanu** [comment]
@mabdelndi can you please post a short usage example that reproduces this?

**Comment by mabdelndi** [comment]
Actually the thing is that when trying to send request continuosly for 60 seg, it stops sending them at a certain time, as i obeserved around 40 seg. What im doing to reproduce this is just using the test_local_many() from your code and adapting it 

`@gen.coroutine
def test_local_many(n):

    cond = CounterCondition()
    timeout = time.time() + 60
    msisdnoffset = 2000000
    mbrDownlink = 500000
    mbrUplink = 500000
    i = 0

    #def future_done(future):
    #    try:
    #        r = future.result()
    #    except Exception as e:
    #        r = e

    #    logging.info(['REQUEST FINISHED', r])

    #    cond.increment(value=1)

    client = AsyncHTTP2Client(
        host='136.225.76.236', port=8543, secure=False,
        verify_certificate=False, max_active_requests=10,
        auto_reconnect=False, auto_reconnect_interval=1
    )

    #client.configure("tornado.curl_httpclient.CurlAsyncHTTPClient")

    st = time.time()
    while time.time() < timeout:
	sub_ip_addr = str(IPv4Address(getrandbits(32))) # Generates random IPv4 for every subscriber

	msisdnoffset = msisdnoffset +1
	mbrUplink = mbrUplink + 1
         
	mbrUplink = mbrUplink + 1

        i = i +1

	jason = '{{"EPC_IpSessions":[{{"apnId":"100.200.110.45","applicationId":1,"capabilities":5,"contentFiltering":4,"correlatedIPv4":"1.1.1.1","creationTT":-1,"emergencySession":false,"installedServices":"e2F2cF9jb3VudCA6IDUsIGF2","ipAddr":"{}@100.200.110.45@esmdx2000000.gxrel10plusrealm.com","lastActivityTT":"","mastership":0,"modificationTime":-1,"mpsSessionType":-1,"originHost":"sapcOwnHostId.operatorRealm.com","originStateId":-1,"pccRulesModificationTime":-1,"peerId":"esmdx2000000.gxrel10plusrealm.com@nodeHostRealm.com","calculatedArpPci":"1","calculatedArpPri":"0","calculatedArpPvi":"-1","calculatedQciCi":"9","calculatedQciGbrDl":"100000","calculatedQciGbrUl":"150000","calculatedQciMbrDl":"1100000","calculatedQciMbrUl":"500000","calculatedQoS":"200000","mbrDownlink":"300000","mbrUplink":"400000","reauthTime":-1,"reauthTimeSource":"","sessionId":"55555{:d};BAT200;esmdx2000000.gxrel10plusrealm.com;902000000","sessionInfoModificationTime":-1,"specificData":"e2F2cF9jb3VudCA6IDUsIGF2cHMgOiBbe2Rlc2NyaXB0aW9uIDogU2Vzc2lvbi1JZH1dfQ==","subscriberId":"55555{:d}","subscriptionType":0,"userEquipmentInfo":"Terminal1","version":"vX.X"}}],"ip":"{}","ipAddrs":["{}@100.200.110.45@55555{:d}"],"subsId":"55555{:d}","afSessionKeys":["*DefaultBearARP:15--*DefaultBearQCI:9--"],"apnId":"100.200.110.45","bberfIds":[],"emergencySession":false,"ipAddr":"{}@100.200.110.45@55555{:d}","pcefIds":["esmdx2000000.gxrel10plusrealm.com"],"specificData":"e2F2cF9jb3VudCA6IDUsIGF2cHMgOiBbe2Rlc2NyaXB0aW9uIDogU2Vzc2lvbi1JZH1dfQ==","trafficType":1,"userIdType":-1,"version":"vX.X"}}'.format(sub_ip_addr,msisdnoffset,msisdnoffset,sub_ip_addr,sub_ip_addr,msisdnoffset,msisdnoffset,sub_ip_addr,msisdnoffset)

	jason_updated = jason_update = '{{"EPC_IpSessions":[{{"apnId":"100.200.110.45","applicationId":1,"capabilities":5,"contentFiltering":4,"correlatedIPv4":"1.1.1.1","creationTT":-1,"emergencySession":false,"installedServices":"e2F2cF9jb3VudCA6IDUsIGF2","ipAddr":"{}@100.200.110.45@esmdx2000000.gxrel10plusrealm.com","lastActivityTT":"","mastership":0,"modificationTime":-1,"mpsSessionType":-1,"originHost":"sapcOwnHostId.operatorRealm.com","originStateId":-1,"pccRulesModificationTime":-1,"peerId":"esmdx2000000.gxrel10plusrealm.com@nodeHostRealm.com","calculatedArpPci":"1","calculatedArpPri":"0","calculatedArpPvi":"-1","calculatedQciCi":"9","calculatedQciGbrDl":"100000","calculatedQciGbrUl":"150000","calculatedQciMbrDl":"1100000","calculatedQciMbrUl":"500000","calculatedQoS":"200000","mbrDownlink":"{:d}","mbrUplink":"{:d}","reauthTime":-1,"reauthTimeSource":"","sessionId":"55555{:d};BAT200;esmdx2000000.gxrel10plusrealm.com;902000000","sessionInfoModificationTime":-1,"specificData":"e2F2cF9jb3VudCA6IDUsIGF2cHMgOiBbe2Rlc2NyaXB0aW9uIDogU2Vzc2lvbi1JZH1dfQ==","subscriberId":"55555{:d}","subscriptionType":0,"userEquipmentInfo":"Terminal1","version":"vX.X"}}],"ip":"{}","ipAddrs":["{}@100.200.110.45@55555{:d}"],"subsId":"55555{:d}","afSessionKeys":["*DefaultBearARP:15--*DefaultBearQCI:9--"],"apnId":"100.200.110.45","bberfIds":[],"emergencySession":false,"ipAddr":"{}@100.200.110.45@55555{:d}","pcefIds":["esmdx2000000.gxrel10plusrealm.com"],"specificData":"e2F2cF9jb3VudCA6IDUsIGF2cHMgOiBbe2Rlc2NyaXB0aW9uIDogU2Vzc2lvbi1JZH1dfQ==","trafficType":1,"userIdType":-1,"version":"vX.X"}}'.format(sub_ip_addr, mbrDownlink, mbrUplink, msisdnoffset,msisdnoffset,sub_ip_addr,sub_ip_addr,msisdnoffset,msisdnoffset,sub_ip_addr,msisdnoffset)

        
	req_put_create = HTTPRequest(
        url='http://136.225.76.236:8543/ldm/v1/subscriber-info/dynamic/55555{:d};BAT200;esmdx2000000.gxrel10plusrealm.com;902000000?interface=gx'.format(msisdnoffset),
            method='PUT',
            request_timeout=0.01,
            body=jason
           )
        req_put_create.headers.parse_line("Content-Type: application/json")
        try:
        	response = yield client.fetch(req_put_create)
                print(i)
        except Exception as e:
                print("Error: %s" % e)
		print(mbrUplink)
    
    
    print("tiempo cumplido") 

    try:
       yield cond.wait_until(n)
    except Exception:
       logging.error('Something bad happened', exc_info=True)

    logging.info(['FINISHED', n, 'requests in', time.time() - st])

class CounterCondition(object):
    def __init__(self):
        self.condition = Condition()
        self.counter = 0

    def increment(self, value=1):
        self.counter += value
        self.condition.notify_all()

    @gen.coroutine
    def wait_until(self, value):
        while True:
            yield self.condition.wait()
            if self.counter >= value:
                self.counter -= value
                return


@gen.coroutine
def main():
    try:
        yield test_local_many(1000)
        # yield test_local()
    except Exception:
        logging.error('Test failed', exc_info=True)


if __name__ == '__main__':
    IOLoop.current().run_sync(main)
`

As you can see using a timeout of 60 seg i send conitnuosly reqs and at some point it breaks and the write buffer stops sending requests. you can reproduce it with this code.

If you need anything else, or more details in the part that is failing in the code let me know
